export const APP_ROUTES = {
  home: '/',
  dashboard: '/',
  appointments: '/appointments',
  doctors: '/doctors',
  patients: '/patients',
  appointmentTypes: '/appointment-types',
  audit: '/audit',
  settings: '/settings',
  schedule: '/schedule',
  myAppointments: '/my-appointments',
  accessibility: '/accessibility',
  login: '/login',
  register: '/register',
  forgotPassword: '/forgot-password',
  accountCreated: '/account-created',
  confirmEmail: '/confirm-email',
  forbidden: '/403',
  notFound: '/404',
} as const;
